version: '3.9'

services:
  php:
    image: php:8.1.33-fpm
    container_name: php81
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    networks:
      - app_net
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.php

  node:
    image: node:17.9.1
    container_name: node17
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app_net
    tty: true

  db:
    image: mariadb:5.5.64
    container_name: mariadb55
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_net

networks:
  app_net:

volumes:
  mariadb_data:
